"""Конфигурация ступени 1: признаки, пресеты, продукты."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODEL_PATH = PROJECT_ROOT / "notebooks" / "alfa_classifier.cbm"

CAT_FEATURES = [
    "smb_type_code",
    "main_okved",
    "okved_major",
    "okved_major_wrapped",
    "categ_name",
    "srvpackage_sale_uk",
    "sourceattr_ccode",
    "city",
    "addrf_region_name",
    "division_name",
    "registration_reason_code",
]

FEATURE_COLS = [
    "smb_type_code",
    "main_okved",
    "okved_major",
    "okved_major_wrapped",
    "okved_cnt_total",
    "okved_groups_unique_cnt",
    "okved_groups_share",
    "days_from_ogrn",
    "days_from_smb",
    "ogrn_days_end_month",
    "ogrn_days_end_quarter",
    "week_sum_transactions",
    "week_mean_transactions",
    "share_last_month",
    "share_last_3_months",
    "categ_name",
    "acquiring_num_live",
    "zpp_num_live",
    "nkop_num_live",
    "rko_num_live",
    "srvpackage_sale_uk",
    "sourceattr_ccode",
    "city",
    "addrf_region_name",
    "postindex_town_code",
    "postindex_area_code",
    "oktmo_reg_code",
    "oktmo_ccode",
    "oktmo_municipality_code",
    "kpp_region_code",
    "addrf_region_code",
    "branch_eq_ccode",
    "sks_city",
    "division_name",
    "regorg_code",
    "registration_reason_code",
    "pensfund_authority_code",
    "apin_salary_last_days",
    "apin_product_active_days",
    "xpin_start_days",
    "xpin_birth_days",
    "days_from_authperson_registration",
    "apin_status_period_cnt",
    "prev_managers",
    "sparkcompany_uk",
    "accum",
    "impnt",
    "to_activate",
    "complexity",
    "get_scores",
]

# Основные признаки для демо-формы (по global importance из ноутбука)
EDITABLE_FEATURES = [
    "smb_type_code",
    "okved_major_wrapped",
    "okved_major",
    "main_okved",
    "sourceattr_ccode",
    "days_from_ogrn",
    "week_sum_transactions",
    "categ_name",
]

FEATURE_LABELS = {
    "smb_type_code": "Тип субъекта (1=ЮЛ, 2=ИП, 3=КФХ)",
    "okved_major_wrapped": "Отрасль (укрупнённый ОКВЭД)",
    "okved_major": "Отраслевая группа ОКВЭД (2 знака)",
    "main_okved": "Основной ОКВЭД",
    "sourceattr_ccode": "Канал привлечения",
    "days_from_ogrn": "Возраст бизнеса (дней с ОГРН)",
    "week_sum_transactions": "Сумма транзакций за неделю (₽)",
    "categ_name": "Категория расходов / кэшбэка",
}

FEATURE_DESCRIPTIONS = {
    "smb_type_code": "Тип субъекта МСП (ЮЛ / ИП / КФХ)",
    "main_okved": "Основной ОКВЭД",
    "okved_major": "Отраслевая группа ОКВЭД (2 знака)",
    "okved_major_wrapped": "Отрасль основного ОКВЭД",
    "okved_cnt_total": "Количество всех ОКВЭД",
    "okved_groups_unique_cnt": "Количество уникальных групп ОКВЭД",
    "okved_groups_share": "Доля основных групп ОКВЭД",
    "days_from_ogrn": "Дней с регистрации бизнеса (ОГРН)",
    "days_from_smb": "Дней в реестре МСП",
    "ogrn_days_end_month": "Дней с регистрации ОГРН до конца месяца",
    "ogrn_days_end_quarter": "Дней с регистрации ОГРН до конца квартала",
    "week_sum_transactions": "Сумма дебетовых транзакций за неделю (₽)",
    "week_mean_transactions": "Количество транзакций за неделю",
    "share_last_month": "Доля транзакций за последний месяц",
    "share_last_3_months": "Доля транзакций за 3 месяца",
    "categ_name": "Категория кэшбэка / расходов",
    "acquiring_num_live": "Действующих эквайринговых продуктов",
    "zpp_num_live": "Действующих зарплатных проектов",
    "nkop_num_live": "Действующих продуктов «Налоговая копилка»",
    "rko_num_live": "Действующих расчётных счетов",
    "srvpackage_sale_uk": "Пакет услуг на старте",
    "sourceattr_ccode": "Канал привлечения клиента",
    "city": "Город",
    "addrf_region_name": "Регион",
    "postindex_town_code": "Почтовый код города",
    "postindex_area_code": "Почтовый код района",
    "oktmo_reg_code": "Код региона ОКТМО",
    "oktmo_ccode": "Код ОКТМО",
    "oktmo_municipality_code": "Код муниципалитета ОКТМО",
    "kpp_region_code": "Регион постановки на учёт (КПП)",
    "addrf_region_code": "Код региона проживания",
    "branch_eq_ccode": "Код филиала банка",
    "sks_city": "Код города (СКС)",
    "division_name": "Клиентское подразделение",
    "regorg_code": "Код органа регистрации (СОУН)",
    "registration_reason_code": "Причина постановки на учёт (КПП)",
    "pensfund_authority_code": "Код терр. органа Пенсионного фонда",
    "apin_salary_last_days": "Среднее дней с последнего зачисления ФОТ",
    "apin_product_active_days": "Среднее дней с даты активации продукта",
    "xpin_start_days": "Среднее дней с даты открытия руководителей",
    "xpin_birth_days": "Среднее дней с даты рождения руководителей",
    "days_from_authperson_registration": "Дней регистрации управляющего",
    "apin_status_period_cnt": "Среднее месяцев в статусе у руководителей",
    "prev_managers": "Количество предыдущих управляющих",
    "sparkcompany_uk": "ID клиента в системе СПАРК",
    "accum": "Признак накопительного продукта",
    "impnt": "Индекс важности клиента",
    "to_activate": "Флаг требует активации",
    "complexity": "Сложность профиля клиента",
    "get_scores": "Скоринговый балл",
}

CLASS_DESCRIPTIONS = {
    "P1": "🏪 Розничный продавец",
    "P2": "💻 IT / Онлайн-бизнес",
    "P3": "🏗️ Строитель / Подрядчик",
    "P4": "🎓 Фрилансер / Самозанятый ИП",
    "P5": "🌱 Новое ЮЛ / Стартап",
    "P6": "🍽️ Услуги / HoReCa",
    "P7": "🚚 Логистика / Транспорт",
    "P8": "🌾 Агробизнес / КФХ",
}

RECOMMENDED_PRODUCTS = {
    "P1": {"ame": 7, "name": "Торговый эквайринг"},
    "P2": {"ame": 11, "name": "Интернет-эквайринг"},
    "P3": {"ame": 10, "name": "Зарплатный проект"},
    "P4": {"ame": 6, "name": "Подписки платежей"},
    "P5": {"ame": 2, "name": "Знакомство с тарифом"},
    "P6": {"ame": 7, "name": "Торговый эквайринг"},
    "P7": {"ame": 10, "name": "Зарплатный проект"},
    "P8": {"ame": 10, "name": "Зарплатный проект"},
}

# Базовый профиль — остальные признаки фиксируются при демо
DEFAULT_FEATURES = {
    "smb_type_code": "2",
    "main_okved": "47",
    "okved_major": "47",
    "okved_major_wrapped": "retail_trade",
    "okved_cnt_total": 2,
    "okved_groups_unique_cnt": 2,
    "okved_groups_share": 0.8,
    "days_from_ogrn": 400,
    "days_from_smb": 380,
    "ogrn_days_end_month": 12,
    "ogrn_days_end_quarter": 40,
    "week_sum_transactions": 130000,
    "week_mean_transactions": 18,
    "share_last_month": 0.55,
    "share_last_3_months": 0.72,
    "categ_name": "grocery",
    "acquiring_num_live": "0",
    "zpp_num_live": "0",
    "nkop_num_live": "0",
    "rko_num_live": "1",
    "srvpackage_sale_uk": "standard",
    "sourceattr_ccode": "branch",
    "city": "Краснодар",
    "addrf_region_name": "Краснодарский край",
    "postindex_town_code": 350000,
    "postindex_area_code": 350,
    "oktmo_reg_code": 23,
    "oktmo_ccode": 37000000,
    "oktmo_municipality_code": 3712,
    "kpp_region_code": 23,
    "addrf_region_code": 23,
    "branch_eq_ccode": 45,
    "sks_city": 120,
    "division_name": "МСБ_Юг",
    "regorg_code": 2310,
    "registration_reason_code": "1",
    "pensfund_authority_code": 23,
    "apin_salary_last_days": 120,
    "apin_product_active_days": 350,
    "xpin_start_days": 900,
    "xpin_birth_days": 14600,
    "days_from_authperson_registration": 700,
    "apin_status_period_cnt": 10,
    "prev_managers": 1,
    "sparkcompany_uk": 4123456,
    "accum": 0.3,
    "impnt": 0.6,
    "to_activate": 1,
    "complexity": 0.4,
    "get_scores": 0.62,
}

# 5 демо-пресетов для быстрого заполнения формы
DEMO_PRESETS = [
    {
        "id": "retail",
        "title": "🏪 Розничный ИП",
        "description": "Торговая точка, ОКВЭД 47, канал branch",
        "overrides": {
            "smb_type_code": "2",
            "main_okved": "47",
            "okved_major": "47",
            "okved_major_wrapped": "retail_trade",
            "sourceattr_ccode": "branch",
            "days_from_ogrn": 400,
            "week_sum_transactions": 130000,
            "categ_name": "grocery",
        },
    },
    {
        "id": "it_online",
        "title": "💻 IT / Онлайн",
        "description": "Разработка ПО, онлайн-канал, средний оборот",
        "overrides": {
            "smb_type_code": "2",
            "main_okved": "62",
            "okved_major": "62",
            "okved_major_wrapped": "it_software",
            "sourceattr_ccode": "online",
            "days_from_ogrn": 500,
            "week_sum_transactions": 250000,
            "categ_name": "software",
        },
    },
    {
        "id": "construction",
        "title": "🏗️ Строитель",
        "description": "Подрядчик, высокий недельный оборот",
        "overrides": {
            "smb_type_code": "1",
            "main_okved": "43",
            "okved_major": "43",
            "okved_major_wrapped": "construction",
            "sourceattr_ccode": "branch",
            "days_from_ogrn": 1200,
            "week_sum_transactions": 1500000,
            "categ_name": "fuel",
        },
    },
    {
        "id": "startup",
        "title": "🌱 Новое ЮЛ",
        "description": "Молодой бизнес < 90 дней, минимальный оборот",
        "overrides": {
            "smb_type_code": "1",
            "main_okved": "15",
            "okved_major": "10",
            "okved_major_wrapped": "various",
            "sourceattr_ccode": "branch",
            "days_from_ogrn": 39,
            "week_sum_transactions": 14153,
            "categ_name": "misc",
        },
    },
    {
        "id": "agro",
        "title": "🌾 Агробизнес / КФХ",
        "description": "Сельхоз, КФХ, сезонные расходы",
        "overrides": {
            "smb_type_code": "3",
            "main_okved": "01",
            "okved_major": "01",
            "okved_major_wrapped": "agriculture",
            "sourceattr_ccode": "branch",
            "days_from_ogrn": 2500,
            "week_sum_transactions": 800000,
            "categ_name": "agro_supplies",
        },
    },
]

# Варианты для select-полей в UI
FIELD_OPTIONS = {
    "smb_type_code": [
        {"value": "1", "label": "1 — Юридическое лицо"},
        {"value": "2", "label": "2 — ИП"},
        {"value": "3", "label": "3 — КФХ"},
    ],
    "okved_major_wrapped": [
        {"value": "retail_trade", "label": "retail_trade — розница"},
        {"value": "it_software", "label": "it_software — IT"},
        {"value": "construction", "label": "construction — строительство"},
        {"value": "consulting", "label": "consulting — консалтинг"},
        {"value": "agriculture", "label": "agriculture — сельхоз"},
        {"value": "horeca", "label": "horeca — общепит"},
        {"value": "logistics", "label": "logistics — логистика"},
        {"value": "freelance_services", "label": "freelance_services — услуги"},
        {"value": "various", "label": "various — разное"},
    ],
    "sourceattr_ccode": [
        {"value": "branch", "label": "branch — отделение"},
        {"value": "online", "label": "online — сайт"},
        {"value": "mobile", "label": "mobile — приложение"},
        {"value": "api", "label": "api — партнёрский API"},
        {"value": "call_center", "label": "call_center — кол-центр"},
    ],
    "categ_name": [
        {"value": "grocery", "label": "grocery — продукты"},
        {"value": "software", "label": "software — ПО"},
        {"value": "fuel", "label": "fuel — топливо"},
        {"value": "office", "label": "office — офис"},
        {"value": "agro_supplies", "label": "agro_supplies — агро"},
        {"value": "restaurant", "label": "restaurant — ресторан"},
        {"value": "digital_services", "label": "digital_services — digital"},
        {"value": "misc", "label": "misc — прочее"},
    ],
}
